name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd /var/www/your-project

            echo "Pulling latest changes..."
            git pull origin main

            echo "Running composer update..."
            composer update --no-interaction --prefer-dist --optimize-autoloader

            echo "Clearing cache..."
            php artisan config:clear || true
            php artisan cache:clear || true

            echo "Done!"
          EOF
